#!/usr/bin/env node

import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, extname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  DEFAULT_AGENT_DIR,
  DEFAULT_CONFIG_FILE,
  DEFAULT_PERMISSIONS,
  loadAgentConfig,
  loadPermissions,
  normalizePermissions,
  resolveDependencies,
} from '@ai-coding-agent/config';
import {
  checkDependencies,
  classifyTask,
  createDependencyPlan,
  getRequiredSkills,
  getRuntimeAdapter,
  inspectProject,
  listWorkflows,
  loadWorkflow,
  resolveWorkflow,
  type WorkflowContext,
} from '@ai-coding-agent/core';

const cwd = process.cwd();
const [command, ...args] = process.argv.slice(2);
function templateDir(): string { return resolve(dirname(fileURLToPath(import.meta.url)), '../../../templates/project/.aca'); }
function specsDir(): string { return join(cwd, DEFAULT_AGENT_DIR, 'specs'); }
function init(): void { const target = join(cwd, DEFAULT_AGENT_DIR); if (existsSync(target)) { console.error(`ACA: ${DEFAULT_AGENT_DIR}/ already exists. Nothing changed.`); process.exitCode = 1; return; } mkdirSync(target, { recursive: true }); cpSync(templateDir(), target, { recursive: true }); console.log(`Created ${DEFAULT_AGENT_DIR}/`); console.log(`Detected project: ${inspectProject(cwd).type}`); }
function resolveProjectDependencies() { const project = inspectProject(cwd); if (!project.hasAgentConfig) return { project, dependencies: undefined }; const config = loadAgentConfig(cwd); const type = config.project?.type && config.project.type !== 'auto' ? config.project.type : project.type; return { project, dependencies: resolveDependencies(config, type) }; }
function status(): void { const { project, dependencies } = resolveProjectDependencies(); console.log('ACA status'); console.log(`  Project:         ${project.type}`); console.log(`  Package manager: ${project.packageManager}`); console.log(`  Config:          ${project.hasAgentConfig ? 'ready' : 'missing'}`); if (!dependencies) return; const config = loadAgentConfig(cwd); console.log(`  Workflow:        ${config.workflow?.default ?? 'not configured'}`); console.log(`  Runtime:         ${config.runtime?.default ?? 'not configured'}`); console.log(`  Skills:          ${dependencies.skills?.join(', ') || 'none'}`); console.log(`  MCP:             ${dependencies.mcp?.join(', ') || 'none'}`); console.log(`  CLI:             ${dependencies.cli?.join(', ') || 'none'}`); }
async function install(): Promise<void> { const { project, dependencies } = resolveProjectDependencies(); if (!dependencies) { console.error(`ACA: ${DEFAULT_AGENT_DIR}/${DEFAULT_CONFIG_FILE} not found. Run "aca init" first.`); process.exitCode = 1; return; } const results = await checkDependencies(createDependencyPlan(dependencies), cwd); console.log(`ACA install (${project.type})`); for (const kind of ['skills', 'mcp', 'cli'] as const) { const items = results.filter((result) => result.kind === kind); console.log(`\n${labelFor(kind)}`); if (!items.length) { console.log('  - none'); continue; } for (const item of items) console.log(`  ${item.installed ? '✓' : '✗'} ${item.name}${item.detail ? ` — ${item.detail}` : ''}`); } const missing = results.filter((result) => !result.installed); if (missing.length) { console.log(`\n发现 ${missing.length} 个缺失依赖。当前版本只检查状态，不会自动修改外部环境。`); process.exitCode = 1; } else console.log('\n所有已声明依赖均已找到。'); }
async function syncRuntime(): Promise<void> { if (!existsSync(join(cwd, DEFAULT_AGENT_DIR, DEFAULT_CONFIG_FILE))) { console.error(`ACA: ${DEFAULT_AGENT_DIR}/${DEFAULT_CONFIG_FILE} not found. Run "aca init" first.`); process.exitCode = 1; return; } const config = loadAgentConfig(cwd); const runtimeName = config.runtime?.default ?? 'claude'; const runtime = getRuntimeAdapter(runtimeName); if (!runtime) { console.error(`ACA: Unsupported runtime: ${runtimeName}`); process.exitCode = 1; return; } const permissions = normalizePermissions(loadPermissions(cwd) ?? DEFAULT_PERMISSIONS); const result = await runtime.sync({ cwd, permissions }); console.log(`ACA sync (${result.runtime})`); for (const file of result.files) console.log(`  ✓ ${file}`); }
function workflowList(): void { const workflows = listWorkflows(cwd); if (!workflows.length) { console.log('暂无 Workflow。'); return; } for (const workflow of workflows) console.log(workflow); }
function workflowShow(name?: string): void { if (!name) { console.error('用法: aca workflow show <name>'); process.exitCode = 1; return; } try { const workflow = loadWorkflow(name, cwd); console.log(`Workflow: ${workflow.name}`); console.log(`Level:    ${workflow.taskLevel}`); console.log(`Type:     ${workflow.taskType ?? 'any'}`); for (const step of workflow.steps) console.log(`  ${step.required ? '✓' : '○'} ${step.id}: ${step.skills.join(', ') || 'none'}`); } catch (error) { console.error(`ACA: ${error instanceof Error ? error.message : String(error)}`); process.exitCode = 1; } }
function taskCheck(description?: string): void { if (!description?.trim()) { console.error('用法: aca task check <任务描述>'); process.exitCode = 1; return; } const classification = classifyTask({ description }); const { project, dependencies } = resolveProjectDependencies(); const context: WorkflowContext = { taskLevel: classification.level, taskType: classification.type, projectType: project.type }; try { const workflow = resolveWorkflow(context, cwd); const projectSkills = dependencies?.skills ?? []; console.log('ACA task check'); console.log(`  Task:     ${description}`); console.log(`  Type:     ${classification.type}`); console.log(`  Level:    ${classification.level}`); if (classification.reasons.length) { console.log('  Reasons:'); for (const reason of classification.reasons) console.log(`    - ${reason}`); } console.log(`  Workflow: ${workflow.name}`); console.log(`  Skills:   ${getRequiredSkills(workflow, projectSkills).join(', ') || 'none'}`); console.log('\n  Gates:'); console.log(`    ${classification.requiresSpec ? '✓' : '○'} Spec`); console.log(`    ${classification.requiresRollbackPlan ? '✓' : '○'} Rollback Plan`); console.log(`    ${classification.requiresSecurityReview ? '✓' : '○'} Security Review`); console.log(`    ${classification.requiresFullVerification ? '✓' : '○'} Full Verification`); console.log('\nSteps:'); for (const step of workflow.steps) console.log(`  ${step.required ? '✓' : '○'} ${step.id} — ${step.description ?? step.skills.join(', ')}`); } catch (error) { console.error(`ACA: ${error instanceof Error ? error.message : String(error)}`); process.exitCode = 1; } }
function labelFor(kind: 'skills' | 'mcp' | 'cli'): string { return kind === 'skills' ? 'Skills:' : kind === 'mcp' ? 'MCP:' : 'CLI:'; }
async function doctor(): Promise<void> { const project = inspectProject(cwd); console.log('ACA doctor'); let failed = false; const check = (ok: boolean, message: string) => { console.log(`  ${ok ? '✓' : '✗'} ${message}`); failed ||= !ok; }; check(project.type !== 'unknown', `project type: ${project.type}`); check(project.hasAgentConfig, `${DEFAULT_AGENT_DIR}/${DEFAULT_CONFIG_FILE} exists`); if (!project.hasAgentConfig) { process.exitCode = 1; return; } let config; try { config = loadAgentConfig(cwd); check(true, 'agent.yaml is valid'); } catch (error) { check(false, `agent.yaml: ${error instanceof Error ? error.message : String(error)}`); process.exitCode = 1; return; } const runtimeName = config.runtime?.default ?? 'claude'; check(Boolean(getRuntimeAdapter(runtimeName)), `runtime: ${runtimeName}`); const permissions = loadPermissions(cwd); check(Boolean(permissions), `${DEFAULT_AGENT_DIR}/permissions.yaml exists`); if (permissions) { const normalized = normalizePermissions(permissions); check(normalized.permissions.allow.length > 0, 'permissions.allow is not empty'); check(!normalized.permissions.deny.some((rule) => normalized.permissions.allow.includes(rule)), 'permissions allow/deny do not directly overlap'); } const type = config.project?.type && config.project.type !== 'auto' ? config.project.type : project.type; const results = await checkDependencies(createDependencyPlan(resolveDependencies(config, type)), cwd); for (const result of results) check(result.installed, `${result.kind}: ${result.name}${result.detail ? ` (${result.detail})` : ''}`); const claudeSettings = join(cwd, '.claude', 'settings.json'); if (runtimeName === 'claude') check(existsSync(claudeSettings), '.claude/settings.json synchronized'); process.exitCode = failed ? 1 : 0; }
function specCreate(name?: string): void { if (!name) { console.error('用法: aca spec create <name>'); process.exitCode = 1; return; } const safeName = normalizeSpecName(name); if (!safeName) { console.error('ACA: Spec 名称只能包含字母、数字、点、下划线和短横线。'); process.exitCode = 1; return; } const directory = specsDir(); mkdirSync(directory, { recursive: true }); const target = join(directory, `${safeName}.md`); if (existsSync(target)) { console.error(`ACA: Spec 已存在: ${safeName}`); process.exitCode = 1; return; } const template = join(templateDir(), 'specs', 'SPEC.md'); writeFileSync(target, readFileSync(template, 'utf8').replace(/^# 任务规格/m, `# ${safeName}`), 'utf8'); console.log(`Created ${DEFAULT_AGENT_DIR}/specs/${safeName}.md`); }
function specList(): void { if (!existsSync(specsDir())) { console.log('暂无 Spec。'); return; } const specs = readdirSync(specsDir(), { withFileTypes: true }).filter((entry) => entry.isFile() && extname(entry.name) === '.md' && entry.name !== 'SPEC.md').map((entry) => entry.name.slice(0, -3)).sort(); if (!specs.length) { console.log('暂无 Spec。'); return; } for (const spec of specs) console.log(spec); }
function specShow(name?: string): void { if (!name) { console.error('用法: aca spec show <name>'); process.exitCode = 1; return; } const safeName = normalizeSpecName(name); if (!safeName) { console.error('ACA: Spec 名称无效。'); process.exitCode = 1; return; } const target = join(specsDir(), `${safeName}.md`); if (!existsSync(target)) { console.error(`ACA: Spec 不存在: ${safeName}`); process.exitCode = 1; return; } process.stdout.write(readFileSync(target, 'utf8')); }
function normalizeSpecName(name: string): string | null { const normalized = name.trim().replace(/\.md$/i, ''); return /^[a-zA-Z0-9._-]+$/.test(normalized) ? normalized : null; }
async function main(): Promise<void> { switch (command) { case 'init': init(); break; case 'install': await install(); break; case 'sync': await syncRuntime(); break; case 'status': status(); break; case 'doctor': await doctor(); break; case 'workflow': switch (args[0]) { case 'list': workflowList(); break; case 'show': workflowShow(args[1]); break; default: console.log('用法: aca workflow <list|show>'); process.exitCode = 1; } break; case 'task': if (args[0] === 'check') taskCheck(args.slice(1).join(' ')); else { console.log('用法: aca task check <任务描述>'); process.exitCode = 1; } break; case 'spec': switch (args[0]) { case 'create': specCreate(args[1]); break; case 'list': specList(); break; case 'show': specShow(args[1]); break; default: console.log('用法: aca spec <create|list|show>'); process.exitCode = 1; } break; default: console.log('Usage: aca <init|install|sync|status|doctor|workflow|task|spec>'); } }
await main();
